#!/usr/bin/env bash
#
###################################################################
# Autogenerated remove links file
###################################################################
# Removing directory ********************************* /home/iamkarlson/git
delete_link "/home/iamkarlson/git"
# Removing file -------------------------------------- /home/iamkarlson/.gitconfig
delete_link "/home/iamkarlson/.gitconfig"
# Removing file -------------------------------------- /home/iamkarlson/.config/onedrive/config
delete_link "/home/iamkarlson/.config/onedrive/config"
# Removing file -------------------------------------- /home/iamkarlson/.config/onedrive/sync_list
delete_link "/home/iamkarlson/.config/onedrive/sync_list"
# Removing directory ********************************* /home/iamkarlson/.zsh
delete_link "/home/iamkarlson/.zsh"
# Removing file -------------------------------------- /home/iamkarlson/.shellrc
delete_link "/home/iamkarlson/.shellrc"
# Removing file -------------------------------------- /home/iamkarlson/.zshrc
delete_link "/home/iamkarlson/.zshrc"
# Removing file -------------------------------------- /home/iamkarlson/.tmux.conf
delete_link "/home/iamkarlson/.tmux.conf"
# Removing directory ********************************* /home/iamkarlson/.config/espanso
delete_link "/home/iamkarlson/.config/espanso"
# Removing directory ********************************* /home/iamkarlson/.doom.d
delete_link "/home/iamkarlson/.doom.d"
# Removing file -------------------------------------- /home/iamkarlson/.config/kitty/kitty.conf
delete_link "/home/iamkarlson/.config/kitty/kitty.conf"
# Removing file -------------------------------------- /home/iamkarlson/.config/sway/config
delete_link "/home/iamkarlson/.config/sway/config"
# Removing directory ********************************* /home/iamkarlson/.config/sway/config.d
delete_link "/home/iamkarlson/.config/sway/config.d"
# Removing file -------------------------------------- /home/iamkarlson/.config/swaylock/config
delete_link "/home/iamkarlson/.config/swaylock/config"
# Removing file -------------------------------------- /home/iamkarlson/.config/waybar/config
delete_link "/home/iamkarlson/.config/waybar/config"
# Removing file -------------------------------------- /home/iamkarlson/.config/waybar/style.css
delete_link "/home/iamkarlson/.config/waybar/style.css"
# Removing directory ********************************* /home/iamkarlson/.config/rofi
delete_link "/home/iamkarlson/.config/rofi"
# Removing directory ********************************* /home/iamkarlson/.config/swaync
delete_link "/home/iamkarlson/.config/swaync"
