#!/usr/bin/env bash
#
###################################################################
# Autogenerated remove links file
###################################################################
# Removing directory ********************************* /home/iamkarlson/git
delete_link "/home/iamkarlson/git"
# Removing file -------------------------------------- /home/iamkarlson/.gitconfig
delete_link "/home/iamkarlson/.gitconfig"
# Removing file -------------------------------------- /home/iamkarlson/.gitignore
delete_link "/home/iamkarlson/.gitignore"
# Removing file -------------------------------------- /home/iamkarlson/.config/onedrive/config
delete_link "/home/iamkarlson/.config/onedrive/config"
# Removing file -------------------------------------- /home/iamkarlson/.config/onedrive/sync_list
delete_link "/home/iamkarlson/.config/onedrive/sync_list"
# Removing directory ********************************* /home/iamkarlson/.zsh
delete_link "/home/iamkarlson/.zsh"
# Removing file -------------------------------------- /home/iamkarlson/.shellrc
delete_link "/home/iamkarlson/.shellrc"
# Removing file -------------------------------------- /home/iamkarlson/.zshrc
delete_link "/home/iamkarlson/.zshrc"
# Removing file -------------------------------------- /home/iamkarlson/.zprofile
delete_link "/home/iamkarlson/.zprofile"
# Removing file -------------------------------------- /home/iamkarlson/.p10k.zsh
delete_link "/home/iamkarlson/.p10k.zsh"
# Removing file -------------------------------------- /home/iamkarlson/.tmux.conf
delete_link "/home/iamkarlson/.tmux.conf"
# Removing directory ********************************* /home/iamkarlson/.config/espanso
delete_link "/home/iamkarlson/.config/espanso"
# Removing directory ********************************* /home/iamkarlson/.doom.d
delete_link "/home/iamkarlson/.doom.d"
# Removing file -------------------------------------- /home/iamkarlson/.config/kitty/kitty.conf
delete_link "/home/iamkarlson/.config/kitty/kitty.conf"
# Removing directory ********************************* /home/iamkarlson/.config/alacritty
delete_link "/home/iamkarlson/.config/alacritty"
# Removing file -------------------------------------- /home/iamkarlson/.vsvimrc
delete_link "/home/iamkarlson/.vsvimrc"
# Removing file -------------------------------------- /home/iamkarlson/.ideavimrc
delete_link "/home/iamkarlson/.ideavimrc"
# Removing file -------------------------------------- /home/iamkarlson/.vimrc
delete_link "/home/iamkarlson/.vimrc"
# Removing file -------------------------------------- /home/iamkarlson/.gvimrc
delete_link "/home/iamkarlson/.gvimrc"
# Removing file -------------------------------------- /home/iamkarlson/.config/nvim/init.vim
delete_link "/home/iamkarlson/.config/nvim/init.vim"
# Removing file -------------------------------------- /home/iamkarlson/.vim/autocmd.vimrc
delete_link "/home/iamkarlson/.vim/autocmd.vimrc"
# Removing file -------------------------------------- /home/iamkarlson/.vim/plugin-settings.vimrc
delete_link "/home/iamkarlson/.vim/plugin-settings.vimrc"
# Removing file -------------------------------------- /home/iamkarlson/.vim/ide.vimrc
delete_link "/home/iamkarlson/.vim/ide.vimrc"
# Removing file -------------------------------------- /home/iamkarlson/.vim/simple-mapping.vimrc
delete_link "/home/iamkarlson/.vim/simple-mapping.vimrc"
# Removing file -------------------------------------- /home/iamkarlson/.vim/mapping.vimrc
delete_link "/home/iamkarlson/.vim/mapping.vimrc"
# Removing file -------------------------------------- /home/iamkarlson/.config/user-dirs.dirs
delete_link "/home/iamkarlson/.config/user-dirs.dirs"
# Removing directory ********************************* /home/iamkarlson/.config/paru
delete_link "/home/iamkarlson/.config/paru"
# Removing file -------------------------------------- /home/iamkarlson/.config/sway/config
delete_link "/home/iamkarlson/.config/sway/config"
# Removing directory ********************************* /home/iamkarlson/.config/sway/config.d
delete_link "/home/iamkarlson/.config/sway/config.d"
# Removing directory ********************************* /home/iamkarlson/.config/sway/scripts
delete_link "/home/iamkarlson/.config/sway/scripts"
# Removing directory ********************************* /home/iamkarlson/.config/sway/profiles
delete_link "/home/iamkarlson/.config/sway/profiles"
# Removing file -------------------------------------- /home/iamkarlson/.config/swaylock/config
delete_link "/home/iamkarlson/.config/swaylock/config"
# Removing file -------------------------------------- /home/iamkarlson/.config/waybar/config
delete_link "/home/iamkarlson/.config/waybar/config"
# Removing file -------------------------------------- /home/iamkarlson/.config/waybar/style.css
delete_link "/home/iamkarlson/.config/waybar/style.css"
# Removing directory ********************************* /home/iamkarlson/.config/rofi
delete_link "/home/iamkarlson/.config/rofi"
# Removing directory ********************************* /home/iamkarlson/.config/kanshi
delete_link "/home/iamkarlson/.config/kanshi"
# Removing directory ********************************* /home/iamkarlson/.config/swaync
delete_link "/home/iamkarlson/.config/swaync"
# Removing directory ********************************* /home/iamkarlson/.config/swappy
delete_link "/home/iamkarlson/.config/swappy"
# Removing directory ********************************* /home/iamkarlson/.config/workstyle
delete_link "/home/iamkarlson/.config/workstyle"
# Removing directory ********************************* /home/iamkarlson/.config/sworkstyle
delete_link "/home/iamkarlson/.config/sworkstyle"
# Removing file -------------------------------------- /usr/bin/sway_nvidia
delete_link "/usr/bin/sway_nvidia"
# Removing file -------------------------------------- /usr/bin/sway_amd
delete_link "/usr/bin/sway_amd"
# Removing file -------------------------------------- /usr/bin/sway_intel
delete_link "/usr/bin/sway_intel"
# Removing file -------------------------------------- /home/iamkarlson/.local/share/applications/discord.desktop
delete_link "/home/iamkarlson/.local/share/applications/discord.desktop"
# Removing file -------------------------------------- /home/iamkarlson/.local/share/applications/doomemacs.desktop
delete_link "/home/iamkarlson/.local/share/applications/doomemacs.desktop"
# Removing file -------------------------------------- /home/iamkarlson/.local/share/applications/emacsclient.desktop
delete_link "/home/iamkarlson/.local/share/applications/emacsclient.desktop"
# Removing file -------------------------------------- /home/iamkarlson/.local/share/applications/emacsclient-mail.desktop
delete_link "/home/iamkarlson/.local/share/applications/emacsclient-mail.desktop"
# Removing file -------------------------------------- /home/iamkarlson/.local/share/applications/emacs.desktop
delete_link "/home/iamkarlson/.local/share/applications/emacs.desktop"
# Removing file -------------------------------------- /home/iamkarlson/.local/share/applications/emacs-mail.desktop
delete_link "/home/iamkarlson/.local/share/applications/emacs-mail.desktop"
# Removing file -------------------------------------- /home/iamkarlson/.local/share/applications/skypeforlinux.desktop
delete_link "/home/iamkarlson/.local/share/applications/skypeforlinux.desktop"
# Removing directory ********************************* /home/iamkarlson/.thunderbird/y2d13ngf.default-release/chrome
delete_link "/home/iamkarlson/.thunderbird/y2d13ngf.default-release/chrome"
