# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

dotenv: ["tasks/taskfile.env"]

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: "Default greeting command"
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  create-links:
    desc: "Create symbolic links to my config files"
    cmds:
      - sudo ./create_links.sh /home/iamkarlson
    interactive: true

  take-photo-telegram:
    desc: "Take photos with all webcams and send to Telegram"
    cmds:
      - ~/src/dotfiles/hyprland/scripts/apps/take_photo_and_send_to_telegram.sh
