
fallback = ""

[matching]
'alacritty' = ''
'kitty' = ''
'/(?i)slack/' = ''
'/(?i)spotify/' = ''
'/(?i)github/' = ''
'/(?i)rust/' = ''
'/(?i)google/' = ''
'/(?i)private browsing/' = ''
'/(?i)vivaldi.*/' = ''
'/(?i)firefox/' = ''
'chrome' = ''
'/(?i)thunar/' = ''
'/(?i)libreoffice calc/' = ''
'/(?i)libreoffice writer/' = ''
'LibreOffice' = ''
'libreoffice-startcenter' = ''
'/(?i)nvim/' = ''
'/(?i)gthumb/' = ''
'/(?i)calculator/' = ''
'/(?i)transmission/' = ''
'/(?i)videostream/' = ''
'/(?i)mpv/' = ''
'/(?i)music/' = ''
'disk usage' = ''
'/(?i).pdf/' = ''
'Emacs' = ''
"emacs" = ''
'/(?i)telegram/' = ''
'org.telegram.desktop' = ''
'/(?i)keepassxc/'=''
'menu' = ''
'jetbrains-datagrip'=''
'jetbrains-pycharm'=''

'/(?i)(cura)|(ultimaker)/'='󰐫'

'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
